"""OECD FORD taxonomy + cross-disciplinary nodes for the Domain Topology Graph."""

FORD_NODES: list[dict] = [
    # ── NATURAL SCIENCES ──────────────────────────────────────────────────────
    {"id": "nat_math", "domain": "Mathematics", "division": "Natural Sciences",
     "description": "Pure and applied mathematics, statistics, probability theory, numerical analysis, topology"},
    {"id": "nat_cs", "domain": "Computer and Information Sciences", "division": "Natural Sciences",
     "description": "Computer science, information systems, software systems, programming languages, algorithms"},
    {"id": "nat_phys", "domain": "Physical Sciences", "division": "Natural Sciences",
     "description": "Physics, astronomy, astrophysics, nuclear physics, optics, quantum mechanics, condensed matter"},
    {"id": "nat_chem", "domain": "Chemical Sciences", "division": "Natural Sciences",
     "description": "Chemistry, organic chemistry, inorganic chemistry, physical chemistry, analytical chemistry, electrochemistry"},
    {"id": "nat_earth", "domain": "Earth and Environmental Sciences", "division": "Natural Sciences",
     "description": "Geology, geophysics, meteorology, oceanography, climate science, atmospheric science, environmental science"},
    {"id": "nat_bio", "domain": "Biological Sciences", "division": "Natural Sciences",
     "description": "Biology, ecology, evolutionary biology, genetics, molecular biology, botany, zoology, microbiology"},

    # ── ENGINEERING & TECHNOLOGY ──────────────────────────────────────────────
    {"id": "eng_civil", "domain": "Civil Engineering", "division": "Engineering and Technology",
     "description": "Structural engineering, transportation systems, construction, geotechnical engineering, hydraulics, urban infrastructure"},
    {"id": "eng_elec", "domain": "Electrical and Electronic Engineering", "division": "Engineering and Technology",
     "description": "Electrical engineering, electronics, telecommunications, power systems, signal processing, control systems"},
    {"id": "eng_mech", "domain": "Mechanical Engineering", "division": "Engineering and Technology",
     "description": "Mechanical engineering, thermodynamics, fluid mechanics, manufacturing processes, tribology, vibration"},
    {"id": "eng_chem", "domain": "Chemical Engineering", "division": "Engineering and Technology",
     "description": "Process engineering, reaction engineering, separation processes, chemical process design, catalysis"},
    {"id": "eng_mat", "domain": "Materials Engineering", "division": "Engineering and Technology",
     "description": "Materials science, metallurgy, polymers, ceramics, composites, nanomaterials, surface engineering"},
    {"id": "eng_med", "domain": "Medical Engineering", "division": "Engineering and Technology",
     "description": "Biomedical engineering, medical devices, prosthetics, diagnostic imaging, tissue engineering, biomechanics"},
    {"id": "eng_env", "domain": "Environmental Engineering", "division": "Engineering and Technology",
     "description": "Pollution control, waste management, water treatment, environmental remediation, sustainable infrastructure"},
    {"id": "eng_nano", "domain": "Nano-technology", "division": "Engineering and Technology",
     "description": "Nanotechnology, nanofabrication, nanoelectronics, nanomedicine, self-assembly, quantum dots"},
    {"id": "eng_soft", "domain": "Software Engineering", "division": "Engineering and Technology",
     "description": "Software development methodology, system architecture, DevOps, agile development, software testing, reliability"},
    {"id": "eng_aero", "domain": "Aerospace Engineering", "division": "Engineering and Technology",
     "description": "Aeronautics, astronautics, flight dynamics, propulsion systems, spacecraft design, avionics"},
    {"id": "eng_robot", "domain": "Robotics", "division": "Engineering and Technology",
     "description": "Robot design, kinematics, autonomous systems, actuators, sensors, robotic process automation"},

    # ── MEDICAL & HEALTH SCIENCES ─────────────────────────────────────────────
    {"id": "med_basic", "domain": "Basic Medicine", "division": "Medical and Health Sciences",
     "description": "Anatomy, physiology, pharmacology, pathology, immunology, microbiology, biochemistry"},
    {"id": "med_clinical", "domain": "Clinical Medicine", "division": "Medical and Health Sciences",
     "description": "Medical practice, surgery, cardiology, oncology, psychiatry, internal medicine, neurology, pediatrics"},
    {"id": "med_health", "domain": "Health Sciences", "division": "Medical and Health Sciences",
     "description": "Public health, epidemiology, health policy, occupational health, nutrition science, preventive medicine"},
    {"id": "med_biotech", "domain": "Medical Biotechnology", "division": "Medical and Health Sciences",
     "description": "Genomics, proteomics, drug development, gene therapy, diagnostics, personalized medicine"},
    {"id": "med_nursing", "domain": "Nursing and Allied Health", "division": "Medical and Health Sciences",
     "description": "Nursing science, allied health, patient care quality, healthcare management, rehabilitation"},

    # ── AGRICULTURAL SCIENCES ─────────────────────────────────────────────────
    {"id": "agr_main", "domain": "Agriculture, Forestry and Fisheries", "division": "Agricultural Sciences",
     "description": "Crop science, agronomy, soil science, forestry, aquaculture, horticulture, agroecology"},
    {"id": "agr_animal", "domain": "Animal and Dairy Science", "division": "Agricultural Sciences",
     "description": "Animal husbandry, livestock production, dairy science, animal nutrition, poultry science"},
    {"id": "agr_vet", "domain": "Veterinary Science", "division": "Agricultural Sciences",
     "description": "Veterinary medicine, animal disease, zoonotic diseases, food safety, wildlife health"},
    {"id": "agr_biotech", "domain": "Agricultural Biotechnology", "division": "Agricultural Sciences",
     "description": "GM crops, plant genetics, precision agriculture, agricultural genomics, biopesticides"},

    # ── SOCIAL SCIENCES ───────────────────────────────────────────────────────
    {"id": "soc_psych", "domain": "Psychology", "division": "Social Sciences",
     "description": "Cognitive psychology, behavioral psychology, clinical psychology, social psychology, developmental psychology"},
    {"id": "soc_econ", "domain": "Economics and Business", "division": "Social Sciences",
     "description": "Microeconomics, macroeconomics, finance, accounting, management science, entrepreneurship, market design"},
    {"id": "soc_edu", "domain": "Educational Sciences", "division": "Social Sciences",
     "description": "Pedagogy, curriculum design, learning theory, educational psychology, higher education, instructional design"},
    {"id": "soc_soc", "domain": "Sociology", "division": "Social Sciences",
     "description": "Social structures, institutions, culture, social movements, stratification, inequality, demography"},
    {"id": "soc_law", "domain": "Law", "division": "Social Sciences",
     "description": "Legal theory, international law, constitutional law, criminal law, regulatory law, jurisprudence"},
    {"id": "soc_poli", "domain": "Political Science", "division": "Social Sciences",
     "description": "Political theory, comparative politics, international relations, public policy, governance, elections"},
    {"id": "soc_geo", "domain": "Social and Economic Geography", "division": "Social Sciences",
     "description": "Urban geography, economic geography, regional science, human geography, spatial analysis"},
    {"id": "soc_media", "domain": "Media and Communications", "division": "Social Sciences",
     "description": "Journalism, media studies, communication theory, digital media, rhetoric, public relations"},
    {"id": "soc_anth", "domain": "Anthropology", "division": "Social Sciences",
     "description": "Cultural anthropology, social anthropology, ethnography, archaeology, linguistic anthropology"},

    # ── HUMANITIES ────────────────────────────────────────────────────────────
    {"id": "hum_hist", "domain": "History and Archaeology", "division": "Humanities",
     "description": "Historical analysis, archival research, historiography, classical archaeology, cultural heritage"},
    {"id": "hum_lang", "domain": "Languages and Literature", "division": "Humanities",
     "description": "Linguistics, literary theory, comparative literature, translation studies, philology, rhetoric"},
    {"id": "hum_phil", "domain": "Philosophy, Ethics and Religion", "division": "Humanities",
     "description": "Epistemology, ethics, metaphysics, logic, philosophy of mind, philosophy of science, religious studies"},
    {"id": "hum_arts", "domain": "Arts", "division": "Humanities",
     "description": "Visual arts, performing arts, music, design history, film studies, aesthetics, cultural studies"},

    # ── CROSS-DISCIPLINARY & EMERGING ─────────────────────────────────────────
    {"id": "cross_cogni", "domain": "Cognitive Science", "division": "Cross-Disciplinary",
     "description": "Cognition, decision-making, mental representation, perception, language processing, embodied cognition"},
    {"id": "cross_neuro", "domain": "Neuroscience", "division": "Cross-Disciplinary",
     "description": "Brain function, neural circuits, computational neuroscience, neuroimaging, neuroplasticity, connectomics"},
    {"id": "cross_datasi", "domain": "Data Science", "division": "Cross-Disciplinary",
     "description": "Statistical modeling, machine learning, data mining, big data analytics, data visualization, feature engineering"},
    {"id": "cross_bioinf", "domain": "Bioinformatics", "division": "Cross-Disciplinary",
     "description": "Sequence analysis, computational biology, genomics analysis, structural bioinformatics, systems genomics"},
    {"id": "cross_beheco", "domain": "Behavioral Economics", "division": "Cross-Disciplinary",
     "description": "Cognitive biases, heuristics, nudge theory, bounded rationality, prospect theory, loss aversion"},
    {"id": "cross_sysbi", "domain": "Systems Biology", "division": "Cross-Disciplinary",
     "description": "Biological networks, gene regulatory networks, multi-omics integration, synthetic biology, metabolomics"},
    {"id": "cross_sustain", "domain": "Sustainability Science", "division": "Cross-Disciplinary",
     "description": "Climate adaptation, circular economy, sustainable development, energy transition, life cycle assessment"},
    {"id": "cross_urban", "domain": "Urban Studies", "division": "Cross-Disciplinary",
     "description": "Urban planning, smart cities, urbanization dynamics, city governance, housing, urban mobility"},
    {"id": "cross_hci", "domain": "Human-Computer Interaction", "division": "Cross-Disciplinary",
     "description": "User experience design, usability engineering, interface design, human factors, accessibility"},
    {"id": "cross_network", "domain": "Network Science", "division": "Cross-Disciplinary",
     "description": "Complex networks, graph theory applications, social network analysis, scale-free networks, percolation"},
    {"id": "cross_complex", "domain": "Complexity Science", "division": "Cross-Disciplinary",
     "description": "Complex adaptive systems, emergence, chaos theory, agent-based modeling, self-organization"},
    {"id": "cross_orgbeh", "domain": "Organizational Behavior", "division": "Cross-Disciplinary",
     "description": "Leadership, team dynamics, organizational culture, motivation theory, workplace psychology, change management"},
    {"id": "cross_decision", "domain": "Decision Science", "division": "Cross-Disciplinary",
     "description": "Decision theory, risk analysis, game theory, operations research, multi-criteria analysis"},
    {"id": "cross_infosci", "domain": "Information Science", "division": "Cross-Disciplinary",
     "description": "Knowledge organization, information retrieval, ontology engineering, library science, semantic web"},
    {"id": "cross_cyber", "domain": "Cybersecurity", "division": "Cross-Disciplinary",
     "description": "Information security, cryptography, network security, privacy engineering, threat modeling, zero trust"},
    {"id": "cross_ai", "domain": "Artificial Intelligence", "division": "Cross-Disciplinary",
     "description": "Machine learning, deep learning, natural language processing, computer vision, AI safety, reinforcement learning"},
    {"id": "cross_quantum", "domain": "Quantum Computing", "division": "Cross-Disciplinary",
     "description": "Quantum algorithms, quantum hardware, quantum error correction, quantum cryptography, quantum information"},
    {"id": "cross_sts", "domain": "Science and Technology Studies", "division": "Cross-Disciplinary",
     "description": "Sociology of science, technology ethics, innovation policy, responsible innovation, research evaluation"},
    {"id": "cross_epidem", "domain": "Epidemiology", "division": "Cross-Disciplinary",
     "description": "Disease surveillance, causal inference in health, clinical trials, population health, biostatistics"},
    {"id": "cross_fintech", "domain": "Financial Technology", "division": "Cross-Disciplinary",
     "description": "Digital payments, blockchain applications, algorithmic trading, insurtech, decentralized finance"},
    {"id": "cross_logistics", "domain": "Logistics and Supply Chain", "division": "Cross-Disciplinary",
     "description": "Supply chain management, operations management, inventory optimization, last-mile delivery"},
    {"id": "cross_design", "domain": "Design Thinking", "division": "Cross-Disciplinary",
     "description": "Human-centered design, service design, industrial design methodology, UX research, design sprint"},
]

# Mapping from node IDs to Semantic Scholar fieldsOfStudy for edge-weight computation
S2_FIELD_MAP: dict[str, list[str]] = {
    "nat_math": ["Mathematics"],
    "nat_cs": ["Computer Science"],
    "nat_phys": ["Physics"],
    "nat_chem": ["Chemistry"],
    "nat_earth": ["Geology", "Environmental Science"],
    "nat_bio": ["Biology"],
    "eng_civil": ["Engineering"],
    "eng_elec": ["Engineering"],
    "eng_mech": ["Engineering"],
    "eng_chem": ["Engineering", "Chemistry"],
    "eng_mat": ["Materials Science"],
    "eng_med": ["Engineering", "Medicine"],
    "eng_env": ["Engineering", "Environmental Science"],
    "eng_nano": ["Materials Science", "Physics"],
    "eng_soft": ["Computer Science"],
    "eng_aero": ["Engineering", "Physics"],
    "eng_robot": ["Engineering", "Computer Science"],
    "med_basic": ["Medicine", "Biology"],
    "med_clinical": ["Medicine"],
    "med_health": ["Medicine"],
    "med_biotech": ["Biology", "Medicine"],
    "med_nursing": ["Medicine"],
    "agr_main": ["Biology", "Environmental Science"],
    "agr_animal": ["Biology"],
    "agr_vet": ["Medicine", "Biology"],
    "agr_biotech": ["Biology"],
    "soc_psych": ["Psychology"],
    "soc_econ": ["Economics", "Business"],
    "soc_edu": ["Psychology", "Sociology"],
    "soc_soc": ["Sociology"],
    "soc_law": ["Political Science"],
    "soc_poli": ["Political Science"],
    "soc_geo": ["Geography"],
    "soc_media": ["Sociology"],
    "soc_anth": ["Sociology", "History"],
    "hum_hist": ["History"],
    "hum_lang": ["Linguistics"],
    "hum_phil": ["Philosophy"],
    "hum_arts": ["Art"],
    "cross_cogni": ["Psychology", "Computer Science"],
    "cross_neuro": ["Neuroscience", "Biology"],
    "cross_datasi": ["Computer Science", "Mathematics"],
    "cross_bioinf": ["Biology", "Computer Science"],
    "cross_beheco": ["Economics", "Psychology"],
    "cross_sysbi": ["Biology"],
    "cross_sustain": ["Environmental Science"],
    "cross_urban": ["Geography", "Sociology"],
    "cross_hci": ["Computer Science"],
    "cross_network": ["Computer Science", "Mathematics"],
    "cross_complex": ["Physics", "Mathematics"],
    "cross_orgbeh": ["Psychology", "Business"],
    "cross_decision": ["Mathematics", "Economics"],
    "cross_infosci": ["Computer Science"],
    "cross_cyber": ["Computer Science"],
    "cross_ai": ["Computer Science"],
    "cross_quantum": ["Physics", "Computer Science"],
    "cross_sts": ["Sociology"],
    "cross_epidem": ["Medicine", "Biology"],
    "cross_fintech": ["Economics", "Computer Science"],
    "cross_logistics": ["Business", "Computer Science"],
    "cross_design": ["Computer Science", "Art"],
}
